name: PHP Coverage

on:
  workflow_call:

  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: zip
          coverage: xdebug

      - name: Configure GitHub token
        run: composer config github-oauth.github.com "${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: composer install

      - name: Run tests with coverage
        shell: bash
        run: RUN_SASS_SPEC=1 vendor/bin/pest --colors=always --coverage-clover build/logs/clover.xml --exclude-group=performance

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v